// Script para criar tabelas via Supabase REST API (sem precisar de conexão direta pg)
// Usa o service_role key para ter permissão total

import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = 'https://upernlulsbswchlcjqkr.supabase.co';
// Service role key (tem permissão para criar tabelas via RPC)
const SUPABASE_SERVICE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwZXJubHVsc2Jzd2NobGNqcWtyIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczODc1MjU3MywiZXhwIjoyMDU0MzI4NTczfQ.RiHdivCEhh6gWwOg1BNBQbHrqZ9wIEeObCHsqDQn9GE';

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);

async function criarTabelasIndustria() {
    console.log('🚀 Iniciando criação das tabelas de Indústria...\n');

    const sqls = [
        {
            nome: 'Tabela setores',
            sql: `
                CREATE TABLE IF NOT EXISTS public.setores (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nome TEXT NOT NULL UNIQUE,
                    responsavel TEXT,
                    criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW()
                );
                ALTER TABLE public.setores ENABLE ROW LEVEL SECURITY;
                DROP POLICY IF EXISTS "Acesso total setores" ON public.setores;
                CREATE POLICY "Acesso total setores" ON public.setores FOR ALL USING (true);
            `
        },
        {
            nome: 'Tabela maquinas (colunas indústria)',
            sql: `
                ALTER TABLE public.maquinas ADD COLUMN IF NOT EXISTS horimetro_atual INTEGER DEFAULT 0;
                ALTER TABLE public.maquinas ADD COLUMN IF NOT EXISTS status_atual TEXT DEFAULT 'DISPONIVEL';
                ALTER TABLE public.maquinas ADD COLUMN IF NOT EXISTS setor_id BIGINT REFERENCES public.setores(id);
                ALTER TABLE public.maquinas ADD COLUMN IF NOT EXISTS codigo_qr TEXT;
                ALTER TABLE public.maquinas ADD COLUMN IF NOT EXISTS modelo TEXT;
                ALTER TABLE public.maquinas ADD COLUMN IF NOT EXISTS fabricante TEXT;
                ALTER TABLE public.maquinas ADD COLUMN IF NOT EXISTS tag TEXT;
                ALTER TABLE public.maquinas ADD COLUMN IF NOT EXISTS horas_uso_diario NUMERIC DEFAULT 8;
            `
        },
        {
            nome: 'Tabela equipamentos',
            sql: `
                CREATE TABLE IF NOT EXISTS public.equipamentos (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nome TEXT NOT NULL,
                    descricao TEXT,
                    tag TEXT,
                    maquina_id BIGINT REFERENCES public.maquinas(id) ON DELETE CASCADE,
                    horimetro_atual INTEGER DEFAULT 0,
                    criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW()
                );
                ALTER TABLE public.equipamentos ENABLE ROW LEVEL SECURITY;
                DROP POLICY IF EXISTS "Acesso total equipamentos" ON public.equipamentos;
                CREATE POLICY "Acesso total equipamentos" ON public.equipamentos FOR ALL USING (true);
            `
        },
        {
            nome: 'Tabela manutencoes (colunas industria)',
            sql: `
                CREATE TABLE IF NOT EXISTS public.manutencoes (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tipo TEXT DEFAULT 'CORRETIVA',
                    status TEXT DEFAULT 'PENDENTE',
                    prioridade TEXT DEFAULT 'MEDIA',
                    descricao TEXT,
                    descricao_problema TEXT,
                    maquina_id BIGINT REFERENCES public.maquinas(id),
                    equipamento_id BIGINT REFERENCES public.equipamentos(id),
                    solicitante_id BIGINT,
                    tecnico_id BIGINT,
                    data_abertura TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
                    data_conclusao TIMESTAMP WITH TIME ZONE,
                    horimetro_execucao INTEGER,
                    origem TEXT DEFAULT 'INDUSTRIA',
                    criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW()
                );
                ALTER TABLE public.manutencoes ENABLE ROW LEVEL SECURITY;
                DROP POLICY IF EXISTS "Acesso total manutencoes" ON public.manutencoes;
                CREATE POLICY "Acesso total manutencoes" ON public.manutencoes FOR ALL USING (true);
            `
        },
        {
            nome: 'Seed - Setores iniciais',
            sql: `
                INSERT INTO public.setores (nome) VALUES 
                    ('Produção'),
                    ('Embalagem'),
                    ('Manutenção'),
                    ('Almoxarifado')
                ON CONFLICT (nome) DO NOTHING;
            `
        }
    ];

    for (const item of sqls) {
        try {
            const { error } = await supabase.rpc('exec_sql', { sql: item.sql });
            if (error) {
                // Tenta via query direta se RPC não existir
                console.log(`   ⚠️  RPC falhou para "${item.nome}": ${error.message}`);
                console.log(`   → Será necessário rodar no SQL Editor do Supabase.`);
            } else {
                console.log(`   ✅ ${item.nome}`);
            }
        } catch (e) {
            console.log(`   ⚠️  "${item.nome}": ${e.message}`);
        }
    }

    // Verificar o que existe
    console.log('\n🔍 Verificando tabelas criadas...');
    const checks = ['setores', 'maquinas', 'equipamentos', 'manutencoes'];
    for (const tabela of checks) {
        const { error } = await supabase.from(tabela).select('id').limit(1);
        if (error) {
            console.log(`   ❌ ${tabela}: ${error.message}`);
        } else {
            console.log(`   ✅ ${tabela}: OK`);
        }
    }
}

criarTabelasIndustria();
