-- ==============================================================================
-- MIGRACAO V3: MÓDULO DE FROTAS ( VEÍCULOS + LOGISTICA )
-- Integrado ao sistema de Manutenção Industrial existente
-- ==============================================================================

-- 1. TABELA DE VEÍCULOS
CREATE TABLE IF NOT EXISTS public.veiculos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa TEXT NOT NULL UNIQUE,
    tipo TEXT NOT NULL, -- 'CAVALO', 'CARRETA', 'TOCO', 'UTILITARIO'
    marca TEXT,         -- 'VOLVO FH540', 'VW 24.250'
    ano INTEGER,
    
    km_atual INTEGER DEFAULT 0,
    status_atual TEXT DEFAULT 'DISPONIVEL', -- 'DISPONIVEL', 'EM_ROTA', 'MANUTENCAO'
    status_updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    condutor_principal_id BIGINT REFERENCES public.operadores(id),
    
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    ativo BOOLEAN DEFAULT TRUE
);

-- 2. LOG DE STATUS (Histórico de onde o veículo esteve/status)
CREATE TABLE IF NOT EXISTS public.veiculo_status_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    veiculo_id BIGINT REFERENCES public.veiculos(id) ON DELETE CASCADE,
    motorista_id BIGINT REFERENCES public.operadores(id),
    
    status_anterior TEXT,
    novo_status TEXT NOT NULL,
    
    km_registro INTEGER,
    observacao TEXT,
    
    latitude NUMERIC(10, 8),
    longitude NUMERIC(11, 8),
    
    data_log TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. INTEGRAÇÃO COM MANUTENÇÃO (Unificar OS de Máquinas e Veículos)
-- Adiciona coluna veiculo_id na tabela de manutencoes existente
ALTER TABLE public.manutencoes ADD COLUMN IF NOT EXISTS veiculo_id BIGINT REFERENCES public.veiculos(id);

-- Restrição: Uma OS deve ser OU de máquina OU de veículo (não ambos, idealmente)
-- (Opcional) CHECK (maquina_id IS NOT NULL OR veiculo_id IS NOT NULL)

-- 4. POLÍTICAS DE SEGURANÇA (RLS - Permissivo para MVP)
ALTER TABLE public.veiculos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.veiculo_status_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Acesso total veiculos" ON public.veiculos;
CREATE POLICY "Acesso total veiculos" ON public.veiculos FOR ALL USING (true);

DROP POLICY IF EXISTS "Acesso total logs" ON public.veiculo_status_logs;
CREATE POLICY "Acesso total logs" ON public.veiculo_status_logs FOR ALL USING (true);


-- 5. DADOS INICIAIS (SEED)
INSERT INTO public.veiculos (placa, tipo, marca, km_atual, status_atual)
VALUES 
    ('HJE-9090', 'CAVALO', 'VOLVO FH 540', 450000, 'DISPONIVEL'),
    ('POC-1234', 'TRUCADO', 'MERCEDES ATEGO', 120500, 'EM_ROTA')
ON CONFLICT (placa) DO NOTHING;
