import pg from 'pg';
const { Client } = pg;

const connectionString = 'postgresql://postgres:RRDMhNycrDFMxdIl@db.upernlulsbswchlcjqkr.supabase.co:5432/postgres';

const client = new Client({
    connectionString,
    ssl: { rejectUnauthorized: false } // Necessário para Supabase
});

async function setupDatabase() {
    try {
        await client.connect();
        console.log('✅ Conectado ao PostgreSQL com sucesso!');

        // 1. Tabela de OPERADORES
        await client.query(`
      CREATE TABLE IF NOT EXISTS operadores (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome TEXT NOT NULL,
        funcao TEXT NOT NULL,
        produtividade_base DECIMAL(5,2) DEFAULT 0,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        ativo BOOLEAN DEFAULT TRUE
      );
    `);
        console.log(' - Tabela "operadores" verificada/criada.');

        // 2. Tabela de MAQUINAS
        await client.query(`
      CREATE TABLE IF NOT EXISTS maquinas (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome TEXT NOT NULL,
        setor TEXT NOT NULL,
        created_at TIMESTAMPTZ DEFAULT NOW()
      );
    `);
        console.log(' - Tabela "maquinas" verificada/criada.');

        // 3. Tabela de PRODUTOS
        await client.query(`
      CREATE TABLE IF NOT EXISTS produtos (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome TEXT NOT NULL,
        tipo TEXT,
        created_at TIMESTAMPTZ DEFAULT NOW()
      );
    `);
        console.log(' - Tabela "produtos" verificada/criada.');

        // 4. Tabela de LANÇAMENTOS DE PRODUÇÃO
        await client.query(`
      CREATE TABLE IF NOT EXISTS producao_lancamentos (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        operador_id BIGINT REFERENCES operadores(id),
        maquina_id BIGINT REFERENCES maquinas(id),
        produto_id BIGINT REFERENCES produtos(id),
        quantidade DECIMAL(10,2) NOT NULL,
        data_registro TIMESTAMPTZ DEFAULT NOW(),
        created_at TIMESTAMPTZ DEFAULT NOW()
      );
    `);
        console.log(' - Tabela "producao_lancamentos" verificada/criada.');

        // 5. Inserir alguns dados iniciais SE as tabelas estiverem vazias (Seed)
        const resOp = await client.query('SELECT COUNT(*) FROM operadores');
        if (resOp.rows[0].count == 0) {
            console.log(' - Inserindo dados iniciais em Operadores...');
            await client.query(`
            INSERT INTO operadores (nome, funcao, produtividade_base) VALUES 
            ('FCO DA PAZ M ALBUQUERQUE', 'Sup. Prod', 15.0),
            ('REGINALDO SARAIVA RODRIGUES', 'Operador M2', 12.0),
            ('JOSE AIRTON DE SOUSA', 'Operador MAQ 1', 15.0);
        `);
        }

        const resMaq = await client.query('SELECT COUNT(*) FROM maquinas');
        if (resMaq.rows[0].count == 0) {
            console.log(' - Inserindo dados iniciais em Máquinas...');
            await client.query(`
            INSERT INTO maquinas (nome, setor) VALUES 
            ('Empacotadora M1', 'Empacotamento'),
            ('Empacotadora M2', 'Empacotamento'),
            ('Moinho A', 'Moagem');
        `);
        }

        const resProd = await client.query('SELECT COUNT(*) FROM produtos');
        if (resProd.rows[0].count == 0) {
            console.log(' - Inserindo dados iniciais em Produtos...');
            await client.query(`
            INSERT INTO produtos (nome, tipo) VALUES 
            ('Serramil', 'Fardo 10x1kg'),
            ('Flocão', 'Fardo 20x500g');
        `);
        }

        console.log('🚀 BANCO DE DADOS CONFIGURADO COM SUCESSO!');

    } catch (err) {
        console.error('❌ Erro ao configurar banco:', err);
    } finally {
        await client.end();
    }
}

setupDatabase();
