-- ============================================================
-- CRIAR TABELAS INDUSTRIA - Colar no SQL Editor do Supabase
-- https://supabase.com/dashboard/project/upernlulsbswchlcjqkr/sql/new
-- ============================================================

-- 1. SETORES
CREATE TABLE IF NOT EXISTS public.setores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL UNIQUE,
    responsavel TEXT,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.setores ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Acesso total setores" ON public.setores;
CREATE POLICY "Acesso total setores" ON public.setores FOR ALL USING (true);

-- 2. MAQUINAS (adiciona colunas se nao existir)
ALTER TABLE public.maquinas ADD COLUMN IF NOT EXISTS horimetro_atual INTEGER DEFAULT 0;
ALTER TABLE public.maquinas ADD COLUMN IF NOT EXISTS status_atual TEXT DEFAULT 'DISPONIVEL';
ALTER TABLE public.maquinas ADD COLUMN IF NOT EXISTS setor_id BIGINT REFERENCES public.setores(id);
ALTER TABLE public.maquinas ADD COLUMN IF NOT EXISTS codigo_qr TEXT;
ALTER TABLE public.maquinas ADD COLUMN IF NOT EXISTS modelo TEXT;
ALTER TABLE public.maquinas ADD COLUMN IF NOT EXISTS fabricante TEXT;
ALTER TABLE public.maquinas ADD COLUMN IF NOT EXISTS tag TEXT;
ALTER TABLE public.maquinas ADD COLUMN IF NOT EXISTS horas_uso_diario NUMERIC DEFAULT 8;

-- 3. EQUIPAMENTOS
CREATE TABLE IF NOT EXISTS public.equipamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    descricao TEXT,
    tag TEXT,
    maquina_id BIGINT REFERENCES public.maquinas(id) ON DELETE CASCADE,
    horimetro_atual INTEGER DEFAULT 0,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.equipamentos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Acesso total equipamentos" ON public.equipamentos;
CREATE POLICY "Acesso total equipamentos" ON public.equipamentos FOR ALL USING (true);

-- 4. MANUTENCOES
CREATE TABLE IF NOT EXISTS public.manutencoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo TEXT DEFAULT 'CORRETIVA',
    status TEXT DEFAULT 'PENDENTE',
    prioridade TEXT DEFAULT 'MEDIA',
    descricao TEXT,
    descricao_problema TEXT,
    maquina_id BIGINT REFERENCES public.maquinas(id),
    equipamento_id BIGINT REFERENCES public.equipamentos(id),
    solicitante_id BIGINT,
    tecnico_id BIGINT,
    data_abertura TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    data_conclusao TIMESTAMP WITH TIME ZONE,
    horimetro_execucao INTEGER,
    origem TEXT DEFAULT 'INDUSTRIA',
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.manutencoes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Acesso total manutencoes" ON public.manutencoes;
CREATE POLICY "Acesso total manutencoes" ON public.manutencoes FOR ALL USING (true);

-- 5. DADOS INICIAIS
INSERT INTO public.setores (nome) VALUES 
    ('Produção'), ('Embalagem'), ('Manutenção'), ('Almoxarifado')
ON CONFLICT (nome) DO NOTHING;
