-- ==============================================================================
-- MIGRACAO V4: MÓDULO DE INDÚSTRIA ( ÁRVORE DE ATIVOS + HORÍMETRO )
-- Estrutura Hierárquica: Setor -> Máquina -> Equipamento -> Peça
-- ==============================================================================

-- 1. TABELAS DE HIERARQUIA

-- Setores já existe (id, nome), mas vamos garantir
CREATE TABLE IF NOT EXISTS public.setores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL UNIQUE,
    responsavel TEXT,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Máquinas já existe, mas vamos adicionar colunas de Horímetro e Status
-- Se a tabela já existir, esses comandos ALTER TABLE vão adicionar o que falta
ALTER TABLE public.maquinas ADD COLUMN IF NOT EXISTS horimetro_atual INTEGER DEFAULT 0;
ALTER TABLE public.maquinas ADD COLUMN IF NOT EXISTS status_atual TEXT DEFAULT 'DISPONIVEL'; -- 'DISPONIVEL', 'MANUTENCAO', 'PARADA'
ALTER TABLE public.maquinas ADD COLUMN IF NOT EXISTS setor_id BIGINT REFERENCES public.setores(id);
ALTER TABLE public.maquinas ADD COLUMN IF NOT EXISTS codigo_qr TEXT UNIQUE; 
ALTER TABLE public.maquinas ADD COLUMN IF NOT EXISTS modelo TEXT;
ALTER TABLE public.maquinas ADD COLUMN IF NOT EXISTS fabricante TEXT;
ALTER TABLE public.maquinas ADD COLUMN IF NOT EXISTS ano_fabricacao INTEGER;

-- Equipamentos (Sub-conjuntos da Máquina. Ex: Motor Principal, Painel Elétrico)
CREATE TABLE IF NOT EXISTS public.equipamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL, -- Ex: "Motor de Acionamento"
    descricao TEXT,
    tag TEXT, -- Tag físico
    
    maquina_id BIGINT REFERENCES public.maquinas(id) ON DELETE CASCADE,
    
    horimetro_atual INTEGER DEFAULT 0, -- Alguns equipamentos têm horímetro próprio
    
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Peças (Item de Reposição - Pode estar ligado a Equipamento OU Maquina diretamente)
-- Nota: A tabela pecas original era um cadastro geral de estoque. Aqui estamos definindo a ESTRUTURA (Instalação).
-- Vamos criar uma tabela de "estrutura_ativos" ou "pontos_manutencao" para não confundir com o almoxarifado?
-- O usuário pediu "cadastro de peças dentro de equipamentos". Isso é BOM (Bill of Materials).
-- Vamos usar a tabela `pecas` existente como "Estoque/Catálogo" e criar `estrutura_pecas` para a árvore?
-- "semelhante ao cadastro de peças do carros do gestão". No gestão, a tabela Peca tinha `veiculoId`.
-- Então vamos manter simples: A peça da árvore É a peça do estoque alocada.
-- Mas e se eu tiver 2 rolamentos iguais na mesma máquina?
-- Abordagem melhor: `componentes_maquina` (BOM).
-- Mas para simplificar e atender o pedido "semelhante ao gestão":
-- Vamos adicionar os campos na tabela `pecas` existente para permitir que ela seja "filha" de equipamento.

ALTER TABLE public.pecas ADD COLUMN IF NOT EXISTS equipamento_id BIGINT REFERENCES public.equipamentos(id) ON DELETE CASCADE;
-- maquina_id já deve existir ou vamos criar? No script V2 (Manutenção) talvez não tivesse direto.
ALTER TABLE public.pecas ADD COLUMN IF NOT EXISTS maquina_id BIGINT REFERENCES public.maquinas(id) ON DELETE CASCADE;

-- Importante: Uma peça deve pertencer a equipamento OU maquina (ou nenhum, se for estoque solto).


-- 2. PLANOS DE PREVENTIVA (Baseado em Horas)

CREATE TABLE IF NOT EXISTS public.planos_preventiva (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL, -- Ex: "Troca de Óleo 500h"
    descricao TEXT,
    
    intervalo_horas INTEGER NOT NULL, -- Ex: 500
    
    -- O plano pode ser genérico (por modelo de máquina) ou específico
    modelo_maquina TEXT, 
    
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela Pivot: Qual máquina segue qual plano e status atual
CREATE TABLE IF NOT EXISTS public.preventivas_maquinas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    maquina_id BIGINT REFERENCES public.maquinas(id) ON DELETE CASCADE,
    plano_id BIGINT REFERENCES public.planos_preventiva(id) ON DELETE CASCADE,
    
    ultima_execucao_horas INTEGER DEFAULT 0, -- Horímetro da última
    proxima_execucao_horas INTEGER NOT NULL, -- Horímetro da próxima
    
    alerta_antecedencia_horas INTEGER DEFAULT 50, -- Avisar 50h antes
    
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    UNIQUE(maquina_id, plano_id)
);


-- 3. INTEGRAÇÃO COM OS (Manutenção)

-- A tabela manutencoes já tem `maquina_id`.
-- Vamos garantir que tenha `equipamento_id` para OS específica de componente.
ALTER TABLE public.manutencoes ADD COLUMN IF NOT EXISTS equipamento_id BIGINT REFERENCES public.equipamentos(id);

-- Adicionar campo horimetro na OS para registrar o momento
ALTER TABLE public.manutencoes ADD COLUMN IF NOT EXISTS horimetro_execucao INTEGER;


-- 4. POLÍTICAS RLS (Permissivas)

ALTER TABLE public.equipamentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.planos_preventiva ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.preventivas_maquinas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Acesso total equipamentos" ON public.equipamentos;
CREATE POLICY "Acesso total equipamentos" ON public.equipamentos FOR ALL USING (true);

DROP POLICY IF EXISTS "Acesso total planos" ON public.planos_preventiva;
CREATE POLICY "Acesso total planos" ON public.planos_preventiva FOR ALL USING (true);

DROP POLICY IF EXISTS "Acesso total preventivas_maquinas" ON public.preventivas_maquinas;
CREATE POLICY "Acesso total preventivas_maquinas" ON public.preventivas_maquinas FOR ALL USING (true);


-- 5. SEED (Dados Iniciais de Exemplo)

-- Setores
INSERT INTO public.setores (nome) VALUES ('Produção'), ('Embalagem') ON CONFLICT (nome) DO NOTHING;

-- Máquinas (Fictício)
-- Assumindo que IDs 1,2,3...
-- Vamos inserir se não existir
INSERT INTO public.maquinas (nome, setor, horimetro_atual, status_atual)
VALUES 
    ('Extrusora A', 'Produção', 5000, 'DISPONIVEL'),
    ('Injetora Beta', 'Produção', 12500, 'MANUTENCAO')
ON CONFLICT DO NOTHING;
-- Nota: 'setor' coluna texto vs 'setor_id'. O script V2 usava texto ou id? 
-- O script V2 (Migration Manutencao) criou tabela setores e adicionou setor_id em maquinas? 
-- Verificando V2: "ALTER TABLE public.maquinas ADD COLUMN IF NOT EXISTS setor_id..."
-- Mas antes tinha "nome TEXT, setor TEXT". Então temos redundância. Vamos priorizar setor_id no futuro.
