-- ==============================================================================
-- MIGRATION CONSOLIDADA ADMIN (TURNOS + OPERADORES)
-- Execute no SQL Editor do Supabase para ativar todas as novas funções.
-- ==============================================================================

-- 1. TABELA DE TURNOS (DADOS DETALHADOS)
CREATE TABLE IF NOT EXISTS public.turnos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    tipo TEXT NOT NULL DEFAULT 'DIRETO',
    inicio_1 TIME NOT NULL,
    fim_1 TIME NOT NULL,
    inicio_2 TIME,
    fim_2 TIME,
    carga_horaria_total INTERVAL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    ativo BOOLEAN DEFAULT TRUE
);

-- 2. AJUSTES NA TABELA DE OPERADORES
ALTER TABLE public.operadores ADD COLUMN IF NOT EXISTS turno TEXT DEFAULT '1º TURNO';
ALTER TABLE public.operadores ADD COLUMN IF NOT EXISTS perfil TEXT DEFAULT 'OPERADOR';
ALTER TABLE public.operadores ALTER COLUMN login DROP NOT NULL;
ALTER TABLE public.operadores ALTER COLUMN senha DROP NOT NULL;

-- 3. SEGURANÇA (RLS)
ALTER TABLE public.turnos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.operadores ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Acesso total turnos" ON public.turnos;
CREATE POLICY "Acesso total turnos" ON public.turnos FOR ALL USING (true);

DROP POLICY IF EXISTS "Acesso total operadores" ON public.operadores;
CREATE POLICY "Acesso total operadores" ON public.operadores FOR ALL USING (true);

-- 4. COMENTÁRIOS
COMMENT ON TABLE public.turnos IS 'Gestão de horários de trabalho e intervalos.';
