-- ==============================================================================
-- MIGRACAO V2: SISTEMA TPM + MULTI-USERS + QR CODE
-- ==============================================================================

-- 1. ATUALIZAR OPERADORES (Login e Senha)
-- Adiciona colunas para acesso ao sistema
ALTER TABLE public.operadores ADD COLUMN IF NOT EXISTS login TEXT UNIQUE; -- Ex: 'joao.silva'
ALTER TABLE public.operadores ADD COLUMN IF NOT EXISTS senha TEXT; -- Ex: '1234' (Para simplificar chão de fábrica)
ALTER TABLE public.operadores ADD COLUMN IF NOT EXISTS perfil TEXT DEFAULT 'OPERADOR'; -- 'ADMIN', 'OPERADOR', 'TECNICO'

-- 2. TABELA DE SETORES (Raiz da Árvore)
CREATE TABLE IF NOT EXISTS public.setores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL UNIQUE,
    responsavel TEXT,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. ATUALIZAR MAQUINAS (Nível 2)
ALTER TABLE public.maquinas ADD COLUMN IF NOT EXISTS setor_id BIGINT REFERENCES public.setores(id);
ALTER TABLE public.maquinas ADD COLUMN IF NOT EXISTS criticidade TEXT CHECK (criticidade IN ('A', 'B', 'C')) DEFAULT 'B';
ALTER TABLE public.maquinas ADD COLUMN IF NOT EXISTS codigo_qr TEXT UNIQUE; -- Identificador único para o QR Code (UUID ou Hash)

-- 4. TABELA DE COMPONENTES (Nível 3)
CREATE TABLE IF NOT EXISTS public.componentes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    maquina_id BIGINT REFERENCES public.maquinas(id) ON DELETE CASCADE,
    especificacao_tecnica TEXT,
    frequencia_preventiva_dias INTEGER,
    proxima_revisao TIMESTAMP WITH TIME ZONE,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. TABELA DE PEÇAS (Nível 4)
CREATE TABLE IF NOT EXISTS public.pecas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    codigo_ref TEXT,
    estoque_atual INTEGER DEFAULT 0,
    estoque_minimo INTEGER DEFAULT 5,
    localizacao TEXT,
    custo_unitario NUMERIC(10,2),
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. RELAÇÃO COMPONENTE <-> PEÇA
CREATE TABLE IF NOT EXISTS componente_pecas (
    componente_id BIGINT REFERENCES public.componentes(id) ON DELETE CASCADE,
    peca_id BIGINT REFERENCES public.pecas(id) ON DELETE CASCADE,
    quantidade_usada INTEGER DEFAULT 1,
    PRIMARY KEY (componente_id, peca_id)
);

-- 7. TABELA PRINCIPAL DE MANUTENÇÃO (OS)
CREATE TABLE IF NOT EXISTS public.manutencoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo TEXT NOT NULL CHECK (tipo IN ('CORRETIVA', 'PREVENTIVA', 'PREDITIVA', 'MELHORIA', 'AUTONOMA')),
    status TEXT NOT NULL DEFAULT 'PENDENTE' CHECK (status IN ('PENDENTE', 'EM_ANDAMENTO', 'AGUARDANDO_PECA', 'CONCLUIDA', 'CANCELADA')),
    prioridade TEXT DEFAULT 'MEDIA',
    maquina_id BIGINT REFERENCES public.maquinas(id),
    componente_id BIGINT REFERENCES public.componentes(id),
    
    solicitante_id BIGINT REFERENCES public.operadores(id),
    tecnico_id BIGINT REFERENCES public.operadores(id),
    
    descricao_problema TEXT,
    diagnostico TEXT,
    solucao_aplicada TEXT,
    
    data_abertura TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    data_inicio TIMESTAMP WITH TIME ZONE,
    data_conclusao TIMESTAMP WITH TIME ZONE,
    tempo_parada_minutos INTEGER DEFAULT 0
);

-- 8. APONTAMENTOS / HISTÓRICO DA OS (Novo!)
-- Permite que o técnico lance atualizações parciais: "Desmontei motor", "Aguardando rolamento", etc.
CREATE TABLE IF NOT EXISTS public.manutencao_apontamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manutencao_id BIGINT REFERENCES public.manutencoes(id) ON DELETE CASCADE,
    tecnico_id BIGINT REFERENCES public.operadores(id),
    descricao TEXT NOT NULL, -- O que foi feito agora
    data_apontamento TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 9. PEÇAS CONSUMIDAS
CREATE TABLE IF NOT EXISTS public.manutencao_consumo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manutencao_id BIGINT REFERENCES public.manutencoes(id) ON DELETE CASCADE,
    peca_id BIGINT REFERENCES public.pecas(id),
    quantidade INTEGER NOT NULL,
    data_uso TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Segurança RLS (Permissiva para protótipo)
ALTER TABLE public.setores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.componentes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pecas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.componente_pecas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.manutencoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.manutencao_apontamentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.manutencao_consumo ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Acesso total setores" ON public.setores;
CREATE POLICY "Acesso total setores" ON public.setores FOR ALL USING (auth.role() = 'authenticated' OR auth.role() = 'anon');
DROP POLICY IF EXISTS "Acesso total componentes" ON public.componentes;
CREATE POLICY "Acesso total componentes" ON public.componentes FOR ALL USING (auth.role() = 'authenticated' OR auth.role() = 'anon');
DROP POLICY IF EXISTS "Acesso total pecas" ON public.pecas;
CREATE POLICY "Acesso total pecas" ON public.pecas FOR ALL USING (auth.role() = 'authenticated' OR auth.role() = 'anon');
DROP POLICY IF EXISTS "Acesso total componente_pecas" ON public.componente_pecas;
CREATE POLICY "Acesso total componente_pecas" ON public.componente_pecas FOR ALL USING (auth.role() = 'authenticated' OR auth.role() = 'anon');
DROP POLICY IF EXISTS "Acesso total manutencoes" ON public.manutencoes;
CREATE POLICY "Acesso total manutencoes" ON public.manutencoes FOR ALL USING (auth.role() = 'authenticated' OR auth.role() = 'anon');
DROP POLICY IF EXISTS "Acesso total manutencao_apontamentos" ON public.manutencao_apontamentos;
CREATE POLICY "Acesso total manutencao_apontamentos" ON public.manutencao_apontamentos FOR ALL USING (auth.role() = 'authenticated' OR auth.role() = 'anon');
DROP POLICY IF EXISTS "Acesso total manutencao_consumo" ON public.manutencao_consumo;
CREATE POLICY "Acesso total manutencao_consumo" ON public.manutencao_consumo FOR ALL USING (auth.role() = 'authenticated' OR auth.role() = 'anon');

-- Atualizar política de operadores para permitir ler login/senha (Cuidado em produção real!)
DROP POLICY IF EXISTS "Enable read access for all users" ON public.operadores;
CREATE POLICY "Enable read access for all users" ON public.operadores FOR SELECT USING (true);
DROP POLICY IF EXISTS "Enable update for all users" ON public.operadores;
CREATE POLICY "Enable update for all users" ON public.operadores FOR UPDATE USING (true);
DROP POLICY IF EXISTS "Enable insert for all users" ON public.operadores;
CREATE POLICY "Enable insert for all users" ON public.operadores FOR INSERT WITH CHECK (true);

-- ==============================================================================
-- 10. CRIAR USUÁRIO ADMIN INICIAL (Para Primeiro Acesso)
-- ==============================================================================
-- Substitua 'admin' e '1234' pelo login e senha desejados
INSERT INTO public.operadores (nome, funcao, login, senha, perfil)
VALUES ('Administrador', 'Gerente', 'admin', '1234', 'ADMIN')
ON CONFLICT (login) DO NOTHING; -- Evita erro se já existir
