-- ==============================================================================
-- MIGRATION V9: GESTÃO DETALHADA DE TURNOS
-- Cria a tabela de turnos com suporte a horários, períodos e carga horária.
-- ==============================================================================

-- 1. CRIAR TABELA DE TURNOS
CREATE TABLE IF NOT EXISTS public.turnos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    tipo TEXT NOT NULL DEFAULT 'DIRETO', -- 'DIRETO' ou 'COMPOSTO'
    inicio_1 TIME NOT NULL,
    fim_1 TIME NOT NULL,
    inicio_2 TIME,
    fim_2 TIME,
    carga_horaria_total INTERVAL, -- Armazena a duração calculada
    created_at TIMESTAMPTZ DEFAULT NOW(),
    ativo BOOLEAN DEFAULT TRUE
);

-- 2. HABILITAR RLS E CRIAR POLÍTICA
ALTER TABLE public.turnos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Acesso total turnos" ON public.turnos;
CREATE POLICY "Acesso total turnos" ON public.turnos FOR ALL USING (true);

-- 3. COMENTÁRIOS PARA DOCUMENTAÇÃO
COMMENT ON TABLE public.turnos IS 'Tabela de gestão de horários e turnos de trabalho.';
COMMENT ON COLUMN public.turnos.tipo IS 'DIRETO (1 período) ou COMPOSTO (2 períodos com intervalo).';
