-- MIGRAÇÃO DE PREVENTIVAS E EQUIPES (V6)

-- 1. Permite guardar múltiplos técnicos que ajudaram na O.S (um array json com os IDs dos ajudantes)
ALTER TABLE public.manutencoes ADD COLUMN IF NOT EXISTS ajudantes JSONB DEFAULT '[]'::jsonb;

-- 2. Tabela autônoma para os Planos de Preventiva da Fábrica
CREATE TABLE IF NOT EXISTS public.planos_preventivos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    maquina_id BIGINT REFERENCES public.maquinas(id) ON DELETE CASCADE,
    tarefa TEXT NOT NULL,
    frequencia_dias INTEGER NOT NULL DEFAULT 30,
    ultima_execucao TIMESTAMP,
    proxima_execucao TIMESTAMP,
    ativo BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
